spring:
  application:
    name: game
  profiles:
    active: dev
  redis:
    database: 8
    cache: redis.dev.xianglin.com
    port: 6379
    session: redis.dev.xianglin.com
  dubbo:
    application:
      name: consumer
    registry:
      address: zookeeper://zookeeper.dev.xianglin.com:2181
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql.dev.xianglin.com:3306/xlgamedb?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: xlgameuser
    password: ure21UgL

logging:
  config: classpath:logback-spring.xml
  path: /data/logs/game
  level:
    root: info
    com.xianglin: debug

landlord:
  room:
    server:
      address:
      - https://game1-dev.xianglin.cn:443/room
      - https://game2-dev.xianglin.cn:443/room

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml